dataset_path: your_dataset_path  # please change
image_path: image_dir/*.png  # please change

nvprof: False
seed: 19260817
adam_alpha_g: 0.001 # 'alpha in Adam optimizer')
adam_alpha_d: 0.003 # 'alpha in Adam optimizer')
adam_beta1: 0.0 # 'beta1 in Adam optimizer')
adam_beta2: 0.999 # 'beta2 in Adam optimizer')
lambda_gp: 1.0 #'Lambda GP')
sn: False
smoothing: 0.999 # '')
keep_smoothed_gen: False # 'Whether to keep a smoothed version of generator.')

batchsize: 32
stage_interval: 0,0,0,0,0,0,0,100000, 150000, 160000, 180000, 300000
max_stage: 11 # 'Size of image.')
iteration: 1000000
#
start_rotation: 2000
start_occlusion_aware: 2000
#
auto_resume: False # 'Whether to automatically resume')
#
ch: 256 # '#Channels')
#
## architecture
generator_architecture: stylegan # stylegan, dcgan, deepvoxels
bigan: False
rotate_conv_input: False
res_dis: True
focal_loss_gamma: 1.
lambda_depth: 10
depth_min: 1.0

## camera parameter prior
## rotation angle range (+-radian)
x_rotate: 0.3054
y_rotate: 1.0472
z_rotate: 0
# translation range
x_translate: 0
y_translate: 0
z_translate: 0

# test angles
test_x_rotate: 0
test_y_rotate: 0.7854
test_z_rotate: 0
test_x_translate: 0
test_y_translate: 0
test_z_translate: 0

## hps (device)
use_mpi: False # 'Whether to use MPI for multi-GPU training.')
comm_name: 'pure_nccl' # 'ChainerMN communicator name')
enable_cuda_profiling: False # 'Whether to enable CUDA profiling.')
#
#
## hps (I/O)
out: 'your_out_dir' # 'Directory to output the result')
auto_resume_dir: '' # 'Directory for loading the saved models')

#
snapshot_interval: 10000 # 'Interval of snapshot')
evaluation_sample_interval: 500 # 'Interval of evaluation sampling')
display_interval: 100 # 'Interval of displaying log to console')
get_model_from_interation: '' # 'Load this iteration (it is a string)')
#
## Style GAN
style_mixing_rate: 0.0 # ' Style Mixing Prob')
enable_blur: False # 'Enable blur function after upscaling/downscaling')

